### ISSUE TITLE
Backup issue after update to v57 "module 're' has no attribute 'Pattern'"

### ISSUE THREAD

**Issue by JvdBBBB** [mail-in-a-box/mailinabox#2131]
After successful update to v57 I get the error "module 're' has no attribute 'Pattern'" via email after the nightly update and when I open de backup status page on maintenance page. The page is not able to load the available backups.

I use Backblaze for backups.

**Comment by noinlijin** [comment]
I have the same error

![image](https://user-images.githubusercontent.com/81671075/173975051-d0b27fe4-0919-4edd-931b-a79f03a35d77.png)

**Comment by finitenamespace** [comment]
Same issue with me after upgrading to V57. 
Noting the latest [Changelog](https://github.com/mail-in-a-box/mailinabox/blob/main/CHANGELOG.md) says this update _fixed_ the Backblaze backup (???), I tried re-running the MIAB config, no luck.
I tried removing the config, deleting the backup caches in /home/user-data/backup/cache, deleting the Backblaze bucket and reconfiguring the Backblaze settings with new API keys, but now MIAB just throws a generic 500 Internal Server Error.

I've found the following in journalctl, if it helps Josh or anyone else at all:

```
Jun 18 10:03:38 box.example.com start[14329]: AttributeError: module 're' has no attribute 'Pattern'
Jun 18 10:03:38 box.example.com python[14329]: Exception on /system/backup/config [POST]
                                                       Traceback (most recent call last):
                                                         File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
                                                           response = self.full_dispatch_request()
                                                         File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
                                                           rv = self.handle_user_exception(e)
                                                         File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
                                                           rv = self.dispatch_request()
                                                         File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
                                                           return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
                                                         File "/root/mailinabox/management/daemon.py", line 75, in newview
                                                           return viewfunc(*args, **kwargs)
                                                         File "/root/mailinabox/management/daemon.py", line 637, in backup_set_custom
                                                           request.form.get('min_age', '')
                                                         File "/root/mailinabox/management/backup.py", line 534, in backup_set_custom
                                                           list_target_files(config)
                                                         File "/root/mailinabox/management/backup.py", line 496, in list_target_files
                                                           from b2sdk.v1 import InMemoryAccountInfo, B2Api
                                                         File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/b2sdk/v1/__init__.py", line 11, in <module>
                                                           from b2sdk.v2 import *  # noqa
                                                         File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/b2sdk/v2/__init__.py", line 11, in <module>
                                                           from b2sdk._v3 import *  # noqa
                                                         File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/b2sdk/_v3/__init__.py", line 170, in <module>
                                                           from b2sdk.sync.folder import AbstractFolder
                                                         File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/b2sdk/sync/folder.py", line 21, in <module>
                                                           from .scan_policies import DEFAULT_SCAN_MANAGER, ScanPoliciesManager
                                                         File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/b2sdk/sync/scan_policies.py", line 108, in <module>
                                                           class ScanPoliciesManager:
                                                         File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/b2sdk/sync/scan_policies.py", line 131, in ScanPoliciesManager
                                                           exclude_uploaded_after: Optional[int] = None,
                                                       AttributeError: module 're' has no attribute 'Pattern'
Jun 18 10:03:38 box.example.com start[14329]: 127.0.0.1 - - [18/Jun/2022 10:03:38] "POST /system/backup/config HTTP/1.0" 500 -

```

**Comment by JoshData** [comment]
I pushed a fix to the main branch. Would appreciate if anyone using Backblaze could try it out.

**Comment by dexbleeker** [comment]
Your latest commit fixed it for me, thanks!

**Comment by JvdBBBB** [comment]
With this update I can access the backup management page without issue again.
