### ISSUE TITLE
v76 management daemon crashes with AttributeError

### ISSUE THREAD

**Issue by Wolf54** [mail-in-a-box/mailinabox#2584]
### Error messages:  
'builtins.Certificate' object has no attribute 'not_valid_before_utc'.

Bug Report: v76 breaks management daemon / admin panel due to cryptography version pin
Mail-in-a-Box Version: v76 Ubuntu Version: 22.04 LTS Upgrade path: v75 → v76

### Description:

After upgrading to v76, the management daemon crashes on startup and the admin control panel returns a 500 Internal Server Error. Mail itself continues to function normally (Postfix/Dovecot/IMAP are unaffected), but the admin panel is completely unusable.

Error output at end of mailinabox setup:

'builtins.Certificate' object has no attribute 'not_valid_before_utc'
...
Traceback (most recent call last):
  File "/root/mailinabox/management/status_checks.py", line 1186, in <module>
    ssl_certificates = get_ssl_certificates(env)
  File "/root/mailinabox/management/ssl_certificates.py", line 98, in get_ssl_certificates
    cert_list.sort(key = lambda cert : (
  File "/root/mailinabox/management/ssl_certificates.py", line 101, in <lambda>
    cert["cert"].not_valid_before_utc <= now <= cert["cert"].not_valid_after_utc,
AttributeError: 'builtins.Certificate' object has no attribute 'not_valid_before_utc'.
Did you mean: 'not_valid_before'?

### Root Cause:

ssl_certificates.py and status_checks.py in v76 were updated to use the timezone-aware not_valid_before_utc and not_valid_after_utc properties introduced in the cryptography library at version 42.x.

However, setup/management.sh still pins the cryptography package to the old version:

"idna>=2.0.0" "cryptography==37.0.2" psutil postfix-mta-sts-resolver cryptography 37.0.2 does not have not_valid_before_utc or not_valid_after_utc. 
Every time mailinabox setup runs, it reinstalls 37.0.2 into the virtualenv, so manually upgrading the package is immediately overwritten on the next setup run.

### Temporary Fix:

Edit setup/management.sh and change the pinned version:

### Find the line (around the pip install block):
grep -n "cryptography" /root/mailinabox/setup/management.sh
Change:        "cryptography==37.0.2"
To:                  "cryptography>=42.0.0"
Using sed:    sed -i 's/"cryptography==37.0.2"/"cryptography>=42.0.0"/' /root/mailinabox/setup/management.sh
Then re-run setup:     mailinabox

Setup will now install cryptography 42.x or later (currently resolves to 48.0.0) into the virtualenv, and the management daemon and admin panel will work correctly.

### Proper Fix:

Update the cryptography pin in setup/management.sh from ==37.0.2 to >=42.0.0 (or pin to a specific known-good version such as ==42.0.8 if a strict pin is preferred).

### Notes:

Mail (send/receive/IMAP) is not affected by this bug. Only the management daemon and admin panel are broken.
Tested working after applying the fix: cryptography upgrades to 48.0.0, setup completes without errors, admin panel loads normally.

**Comment by JoshData** [comment]
> ssl_certificates.py and status_checks.py in v76 were updated to use the timezone-aware not_valid_before_utc and not_valid_after_utc properties

I don't know whether this is AI-generated bullshit or a confusion with a fork.
